### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by khusamov** [LiveTex/Node-Pg#15]
khusamov@cardinal:~/workspace (master) $ npm install livetex-node-pg -g
|

> livetex-node-pg@2.0.1 install /home/ubuntu/.nvm/versions/node/v4.1.0/lib/node_modules/livetex-node-pg
> node-gyp rebuild && make cpp && make js

make: Entering directory `/home/ubuntu/.nvm/versions/node/v4.1.0/lib/node_modules/livetex-node-pg/build'
  CXX(target) Release/obj.target/pg/src/connection.o
../src/connection.cc:11:31: fatal error: jemalloc/jemalloc.h: No such file or directory
 #include <jemalloc/jemalloc.h>
                               ^
compilation terminated.
make: *** [Release/obj.target/pg/src/connection.o] Error 1
make: Leaving directory`/home/ubuntu/.nvm/versions/node/v4.1.0/lib/node_modules/livetex-node-pg/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.14.13-c9
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v4.1.0/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/.nvm/versions/node/v4.1.0/lib/node_modules/livetex-node-pg
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.14.13-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.0/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.0/bin/npm" "install" "livetex-node-pg" "-g"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! livetex-node-pg@2.0.1 install: `node-gyp rebuild && make cpp && make js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the livetex-node-pg@2.0.1 install script 'node-gyp rebuild && make cpp && make js'.
npm ERR! This is most likely a problem with the livetex-node-pg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild && make cpp && make js
npm ERR! You can get their info via:
npm ERR!     npm owner ls livetex-node-pg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
khusamov@cardinal:~/workspace (master) $

**Comment by valeriakononenko** [comment]
u need to install lib jemalloc

**Comment by khusamov** [comment]
thx
