### ISSUE TITLE
Npm installation failed

### ISSUE THREAD

**Issue by aleksandrmelnyk** [LiveTex/Node-Pg#2]
Archive:  .build/google-closure.zip
  inflating: .build/compiler.jar  
which gjslint > /dev/null; \
    [ $? -eq 0 ] || sudo pip install -U http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz;
sudo: pip: command not found
make: **\* [setup-linter] Error 1
npm ERR! livetex-node-pg@1.0.0 install: `make setup && make`
npm ERR! `sh "-c" "make setup && make"` failed with 2
npm ERR! 
npm ERR! Failed at the livetex-node-pg@1.0.0 install script.
npm ERR! This is most likely a problem with the livetex-node-pg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make setup && make
npm ERR! You can get their info via:
npm ERR!     npm owner ls livetex-node-pg
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-27-generic
npm ERR! command "/home/mamay/.nvm/v0.10.3/bin/node" "/home/mamay/.nvm/v0.10.3/bin/npm" "install" "livetex-node-pg"
npm ERR! cwd /home/mamay/projects/kegs-node
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mamay/projects/kegs-node/npm-debug.log
npm ERR! not ok code 0

**Comment by kalachevmax** [comment]
You need to install pip.
http://www.pip-installer.org/en/latest/installing.html

**Comment by aleksandrmelnyk** [comment]
Sorry, installed pip, another error (I am using node under nvm):
java -jar .build/compiler.jar --warning_level VERBOSE --output_wrapper="var querystring = require('querystring'); var __pg = require('./pg.node');  "%output%"  module.exports = pg;" --language_in=ECMASCRIPT5_STRICT --debug --formatting PRETTY_PRINT --externs lib/externs.js --compilation_level WHITESPACE_ONLY \
                   --js lib/pg/pg.js > bin/index.js
gcc  -fno-inline -O3 -Wall -fPIC -DPIC -pthread -I/usr/include/node -I/usr/include/postgresql -I/usr/include/jemalloc -o bin/pg.o  -c src/pg.cc
src/pg.cc:6:18: fatal error: node.h: No such file or directory
compilation terminated.
make: **\* [pg.o] Error 1

**Comment by kononencheg** [comment]
You shoud install `node.h` header into `/usr/include` folder. Usually it installs with node. 

Вы можете продолжать разговор на русском языке.

**Comment by aleksandrmelnyk** [comment]
Удалил nvm 
установил node v0.10.15 
таже ошибка: src/pg.cc:6:18: fatal error: node.h: No such file or directory

**Comment by kononencheg** [comment]
C 10-ой версией плагин не проверялся, попробуйте устновить 8-ую версию.

**Comment by migosm** [comment]
"Удалил nvm 
установил node v0.10.15 
таже ошибка: src/pg.cc:6:18: fatal error: node.h: No such file or directory"

К сожалению в версии 0.10.15 файл node.h из src/ не устанавливается. Скопируйте его из ${source_path}/src/node.h в /usr/include/node/ .

**Comment by aleksandrmelnyk** [comment]
Спасибо, я пока не буду ставить, мы на продакшине испльзуем 0.10.15, нет
возможности руками стаивть файлы.
Конечно хотелось бы поставить альтернативу node-pg, потому что там есть баг
- при нагрузках node-pg может просто не возвращать данные (res.rows.length
  == 0).

2013/8/16 migosm notifications@github.com

**Comment by MatrosSkin** [comment]
Хотел попробовать ваш драйвер и наткнулся на ту же проблему. Node.js v 0.10.17 . Положил node.h  - попросило еще файлик, потом еще... отсановился на ошибке (несколько поседних строк консоли):

gcc  -fno-inline -O3 -Wall -fPIC -DPIC -pthread -I/usr/include/node -I/usr/include/postgresql -I/usr/include/jemalloc -o bin/connection.o  -c src/connection.cc
src/connection.cc: In function ‘void connection_queue_work(connection_t_, uv_work_cb)’:
src/connection.cc:94:75: error: invalid conversion from ‘void (_)(uv_work_t_) {aka void (_)(uv_work_s_)}’ to ‘uv_after_work_cb {aka void (_)(uv_work_s_, int)}’ [-fpermissive]
In file included from src/connection.cc:9:0:
/usr/include/node/uv.h:1432:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t_, uv_work_t_, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
make: *_\* [connection.o] Error 1
npm ERR! weird error 2
npm ERR! not ok code 0

Что скажете? можно ожидать скорого фикса и какой либо другой помощи?

**Comment by EuDgee** [comment]
Fixed. At this moment new version is available only through the git-repository. Npm will be updated a little bit later.

Исправлено. Сейчас обновили только в git'е, чуть позже (как обкатаем наверняка) обновим и npm.
