### ISSUE TITLE
Failed to npm install (there is no apt-get on my system :)

### ISSUE THREAD

**Issue by yurijmikhalevich** [LiveTex/Node-Pg#3]
Trying to npm install livetex-node-pg on fedora having all needed dependencies, but installer tries to execute apt-get to install already installed dependencies.

**Comment by romanesko** [comment]
The same! osx doesn't have apt-get

**Comment by kruatech** [comment]
Cleaning up...
mkdir bin/
java -jar .build/compiler.jar --warning_level VERBOSE --output_wrapper="var querystring = require('querystring'); var __pg = require('./pg.node');  "%output%"  module.exports = pg;" --language_in=ECMASCRIPT5_STRICT --debug --formatting PRETTY_PRINT --externs lib/externs.js --compilation_level WHITESPACE_ONLY \
                   --js lib/pg/pg.js > bin/index.js
/bin/sh: 1: java: not found
make: **\* [index.js] Ошибка 127
npm ERR! livetex-node-pg@1.0.0 install: `make setup && make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the livetex-node-pg@1.0.0 install script.
npm ERR! This is most likely a problem with the livetex-node-pg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make setup && make
npm ERR! You can get their info via:
npm ERR!     npm owner ls livetex-node-pg
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.0-13-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "livetex-node-pg"
npm ERR! cwd /home/anton/project/nodejs/parsing
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/anton/project/nodejs/parsing/npm-debug.log
npm ERR! not ok code 0

Не встает!!!

**Comment by valeriakononenko** [comment]
livetex-node-pg@2.0.0

собирается для node вплоть до 10 версии.
необходимые библиотеки: libpq-dev, libjemalloc-dev

module can be built with 'npm install'. 
it works for node-v0.10.x by means of built-in node-gyp, as well as for v0.8.x.
but you should have preinstalled libpq-dev and libjemalloc-dev.
